dist: xenial

language: python

addons:
  apt:
    packages:
      - doxygen
      - graphviz

deploy:
  provider: pypi
  user: __token__
  distributions: sdist
  password: $PYPI_TOKEN
  on:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+.[0-9]+.[0-9]+.* && $(if grep -q "${BASH_REMATCH:1}" "$TRAVIS_BUILD_DIR/setup.py"; then echo 0; fi)

script:
  - ci/travis-ci-script.sh || travis_terminate 1
